# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geofence_v1alpha1.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'geofence_v1alpha1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17geofence_v1alpha1.proto\x12\x11geofence.v1alpha1\"\xb3\x01\n\x15StreamGeofenceMessage\x12\x45\n\x14wifi_client_geofence\x18\x01 \x01(\x0b\x32%.geofence.v1alpha1.WifiClientGeofenceH\x00\x12\x41\n\x12\x61sset_tag_geofence\x18\x02 \x01(\x0b\x32#.geofence.v1alpha1.AssetTagGeofenceH\x00\x42\x10\n\x0egeofence_event\"\xad\x03\n\x12WifiClientGeofence\x12\x14\n\x07zone_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12H\n\nevent_type\x18\x02 \x01(\x0e\x32/.geofence.v1alpha1.WifiClientGeofence.EventTypeH\x01\x88\x01\x01\x12\x18\n\x0bsta_eth_mac\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x61ssoc_bssid\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x1f\n\x12hashed_sta_eth_mac\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\"\n\x15\x64well_time_in_seconds\x18\x06 \x01(\rH\x05\x88\x01\x01\"R\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x45VENT_TYPE_ENTER\x10\x01\x12\x13\n\x0f\x45VENT_TYPE_EXIT\x10\x02\x42\n\n\x08_zone_idB\r\n\x0b_event_typeB\x0e\n\x0c_sta_eth_macB\x0e\n\x0c_assoc_bssidB\x15\n\x13_hashed_sta_eth_macB\x18\n\x16_dwell_time_in_seconds\"\xc3\x02\n\x10\x41ssetTagGeofence\x12\x14\n\x07zone_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x46\n\nevent_type\x18\x02 \x01(\x0e\x32-.geofence.v1alpha1.AssetTagGeofence.EventTypeH\x01\x88\x01\x01\x12\x16\n\tdevice_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\"\n\x15\x64well_time_in_seconds\x18\x04 \x01(\rH\x03\x88\x01\x01\"R\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x45VENT_TYPE_ENTER\x10\x01\x12\x13\n\x0f\x45VENT_TYPE_EXIT\x10\x02\x42\n\n\x08_zone_idB\r\n\x0b_event_typeB\x0c\n\n_device_idB\x18\n\x16_dwell_time_in_secondsB6\n4com.hpe.gravity.apistreaming.proto.geofence.v1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geofence_v1alpha1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n4com.hpe.gravity.apistreaming.proto.geofence.v1alpha1'
  _globals['_STREAMGEOFENCEMESSAGE']._serialized_start=47
  _globals['_STREAMGEOFENCEMESSAGE']._serialized_end=226
  _globals['_WIFICLIENTGEOFENCE']._serialized_start=229
  _globals['_WIFICLIENTGEOFENCE']._serialized_end=658
  _globals['_WIFICLIENTGEOFENCE_EVENTTYPE']._serialized_start=468
  _globals['_WIFICLIENTGEOFENCE_EVENTTYPE']._serialized_end=550
  _globals['_ASSETTAGGEOFENCE']._serialized_start=661
  _globals['_ASSETTAGGEOFENCE']._serialized_end=984
  _globals['_ASSETTAGGEOFENCE_EVENTTYPE']._serialized_start=468
  _globals['_ASSETTAGGEOFENCE_EVENTTYPE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
